.TH XFCE4-POPUP-WHISKERMENU "1" "October 2013"

.SH "NAME"
xfce4-popup-whiskermenu \- shows Whisker Menu

.SH "SYNOPSIS"
.PP
.B xfce4\-popup\-whiskermenu \-h
.br
.B xfce4\-popup\-whiskermenu \-\-help
.br
.B xfce4\-popup\-whiskermenu \-V
.br
.B xfce4\-popup\-whiskermenu \-\-version
.br
.B xfce4\-popup\-whiskermenu
[ \-\fBp\fR ]

.SH "DESCRIPTION"
.PP
\fBxfce4\-popup\-whiskermenu\fR shows Whisker Menu if at least one Whisker
Menu applet is present on one of your panels.
.PP
The default behavior is to show Whisker Menu near the applet button. If
you have several Whisker Menu applets, only the first one you have set up
will pop up.

.SH "OPTIONS"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options.
.TP
\fB\-p\fR, \fB\-\-pointer\fR
Popup menu at current mouse position.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information and exit.

.SH "COPYRIGHT"
.PP
Copyright \(co 2013 Graeme Gott
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

.SH "AUTHOR"
.PP
Graeme Gott <graeme@gottcode.org>.
.PP
This manual page was derived from the manual page for the Xfce window list
written by Francois Wendling <frwendling@free.fr>.
